import type { StreamState } from "./types.js"

export function getMockSequence(): StreamState[] {
  return [
    {
      num_followers: 980,
      num_followers_total: 1200,
      num_subscribers: 4,
      watching_now: 120,
      is_live: true,
      latest_subscriber_username: null,
      latest_follower_username: null,
      timestamp: Date.now(),
    },
    {
      num_followers: 990,
      num_followers_total: 1210,
      num_subscribers: 4,
      watching_now: 210,
      is_live: true,
      latest_subscriber_username: null,
      latest_follower_username: null,
      timestamp: Date.now(),
    },
    {
      num_followers: 995,
      num_followers_total: 1215,
      num_subscribers: 4,
      watching_now: 340,
      is_live: true,
      latest_subscriber_username: null,
      latest_follower_username: null,
      timestamp: Date.now(),
    },
    {
      num_followers: 1000,
      num_followers_total: 1220,
      num_subscribers: 4,
      watching_now: 380,
      is_live: true,
      latest_subscriber_username: null,
      latest_follower_username: "NewViewer",
      timestamp: Date.now(),
    },
    {
      num_followers: 1000,
      num_followers_total: 1220,
      num_subscribers: 5,
      watching_now: 410,
      is_live: true,
      latest_subscriber_username: "CryptoFan42",
      latest_follower_username: "NewViewer",
      timestamp: Date.now(),
    },
    {
      num_followers: 1001,
      num_followers_total: 1221,
      num_subscribers: 5,
      watching_now: 620,
      is_live: true,
      latest_subscriber_username: "CryptoFan42",
      latest_follower_username: "NewViewer",
      timestamp: Date.now(),
    },
    {
      num_followers: 1002,
      num_followers_total: 1222,
      num_subscribers: 5,
      watching_now: 590,
      is_live: true,
      latest_subscriber_username: "CryptoFan42",
      latest_follower_username: "NewViewer",
      timestamp: Date.now(),
    },
    {
      num_followers: 1002,
      num_followers_total: 1222,
      num_subscribers: 6,
      watching_now: 580,
      is_live: true,
      latest_subscriber_username: "TipbleUser",
      latest_follower_username: "NewViewer",
      timestamp: Date.now(),
    },
  ]
}
